# Model arguments
model_name_or_path: Qwen/Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: GAIR/LIMO
dataset_config: default
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7
experiment_name: GRPO

# GRPO trainer config
bf16: true
beta: 0.05 # RZ: This is the KL penalty parameter.
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.9
do_eval: false
eval_strategy: steps # RZ: LIMO does not have a test split, so we do not evaluate along the way.
eval_ratio: 0.1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen-2.5-1.5B-Simple-RL
hub_strategy: every_save
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
max_grad_norm: 1.0 # RZ: This adapts from YM's codebase
weight_decay: 0.0 # RZ: This adapts from YM's codebase
num_generations: 8 # RZ: This is the G in the GRPO paper.
num_generations_eval: 2
num_train_epochs: 5
per_device_eval_batch_size: 16
per_device_train_batch_size: 16
output_dir: ./results

overwrite_output_dir: true
push_to_hub: false
report_to:
- none
reward_funcs:
- accuracy
reward_weights:
- 1.0
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1
